[versions]
agp = "9.4.1"
kotlin = "2.4.20"
composeMultiplatform = "1.12.1"
androidx-activity = "1.13.0"
miuix = "0.9.4"
miuixBlur = "0.9.4"
miuixSquircle = "0.9.4"
miuixPreference = "0.9.4"
miuixIcons = "0.9.4"

[libraries]
androidx-activity-compose = { module = "androidx.activity:activity-compose", version.ref = "androidx-activity" }
miuix-ui = { module = "top.yukonga.miuix.kmp:miuix-ui", version.ref = "miuix" }
miuix-preference = { module = "top.yukonga.miuix.kmp:miuix-preference", version.ref = "miuixPreference" }
miuix-blur = { module = "top.yukonga.miuix.kmp:miuix-blur", version.ref = "miuixBlur" }
miuix-squircle = { module = "top.yukonga.miuix.kmp:miuix-squircle", version.ref = "miuixSquircle" }
miuix-icons = { module = "top.yukonga.miuix.kmp:miuix-icons", version.ref = "miuixIcons" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
compose-multiplatform = { id = "org.jetbrains.compose", version.ref = "composeMultiplatform" }